services:
  postgres:
    image: postgres:15
    container_name: pld_postgres
    environment:
      POSTGRES_DB: pld_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: